//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Common;
using System.Data.EntityClient;
using System.Data.Metadata.Edm;
using System.Data.Objects.DataClasses;
using System.Data.Objects;
using System.Data;
using System.Diagnostics;
using System.Globalization;
using System.Linq;

namespace NextProjectMVC.Models.Entities
{
    public partial class NEXT_PROJECTEntities : ObjectContext
    {
        public const string ConnectionString = "name=NEXT_PROJECTEntities";
        public const string ContainerName = "NEXT_PROJECTEntities";
    
        #region Constructors
    
        public NEXT_PROJECTEntities()
            : base(ConnectionString, ContainerName)
        {
            Initialize();
        }
    
        public NEXT_PROJECTEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            Initialize();
        }
    
        public NEXT_PROJECTEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            Initialize();
        }
    
        private void Initialize()
        {
            // Creating proxies requires the use of the ProxyDataContractResolver and
            // may allow lazy loading which can expand the loaded graph during serialization.
            ContextOptions.ProxyCreationEnabled = false;
            ObjectMaterialized += new ObjectMaterializedEventHandler(HandleObjectMaterialized);
        }
    
        private void HandleObjectMaterialized(object sender, ObjectMaterializedEventArgs e)
        {
            var entity = e.Entity as IObjectWithChangeTracker;
            if (entity != null)
            {
                bool changeTrackingEnabled = entity.ChangeTracker.ChangeTrackingEnabled;
                try
                {
                    entity.MarkAsUnchanged();
                }
                finally
                {
                    entity.ChangeTracker.ChangeTrackingEnabled = changeTrackingEnabled;
                }
                this.StoreReferenceKeyValues(entity);
            }
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<GroupMember> GroupMembers
        {
            get { return _groupMembers  ?? (_groupMembers = CreateObjectSet<GroupMember>("GroupMembers")); }
        }
        private ObjectSet<GroupMember> _groupMembers;
    
        public ObjectSet<Group> Groups
        {
            get { return _groups  ?? (_groups = CreateObjectSet<Group>("Groups")); }
        }
        private ObjectSet<Group> _groups;
    
        public ObjectSet<Project> Projects
        {
            get { return _projects  ?? (_projects = CreateObjectSet<Project>("Projects")); }
        }
        private ObjectSet<Project> _projects;
    
        public ObjectSet<User> Users
        {
            get { return _users  ?? (_users = CreateObjectSet<User>("Users")); }
        }
        private ObjectSet<User> _users;

        #endregion
    }
}
